
#ifndef OzgGameEatFish_GameConfig_h
#define OzgGameEatFish_GameConfig_h

#include "cocos2d.h"

#define GAME_CONFIG_TRANSITION 0.5f //过场时间

#define GAME_CONFIG_PLAYERS 2 //player默认的生命值
#define GAME_CONFIG_PLAYER_INVINCIBLE 4.0 //玩家的初始化无敌时间
#define GAME_CONFIG_PLAYER_INVINCIBLE2 30.0 //玩家使用道具获得的无敌时间

#define GAME_CONFIG_BGSOUND "GAME_CONFIG_BGSOUND"
#define GAME_CONFIG_EFFECT "GAME_CONFIG_EFFECT"

//动画缓存key
#define GAME_CONFIG_ANIMKEY_PLAYER_FISH "GAME_CONFIG_ANIMKEY_PLAYER_FISH"
#define GAME_CONFIG_ANIMKEY_PLAYER_B_FISH "GAME_CONFIG_ANIMKEY_PLAYER_B_FISH"
#define GAME_CONFIG_ANIMKEY_PLAYER_M_FISH "GAME_CONFIG_ANIMKEY_PLAYER_M_FISH"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH1 "GAME_CONFIG_ANIMKEY_ENEMY_FISH1"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH2 "GAME_CONFIG_ANIMKEY_ENEMY_FISH2"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH3 "GAME_CONFIG_ANIMKEY_ENEMY_FISH3"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH4 "GAME_CONFIG_ANIMKEY_ENEMY_FISH4"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH5 "GAME_CONFIG_ANIMKEY_ENEMY_FISH5"
#define GAME_CONFIG_ANIMKEY_ENEMY_FISH6 "GAME_CONFIG_ANIMKEY_ENEMY_FISH6"
#define GAME_CONFIG_ANIMKEY_JELLY_FISH "GAME_CONFIG_ANIMKEY_JELLY_FISH"
#define GAME_CONFIG_ANIMKEY_ITEM_GOLD "GAME_CONFIG_ANIMKEY_ITEM_GOLD"

#define GAME_CONFIG_ENEMY_JELLYFISH 0.0005 //水母每帧的出现机率 1/2000的机率
//各个AI鱼的出现机率
#define GAME_CONFIG_ENEMY_FISH1 0.05
#define GAME_CONFIG_ENEMY_FISH2 0.05
#define GAME_CONFIG_ENEMY_FISH3 0.00625
#define GAME_CONFIG_ENEMY_FISH4 0.00375
#define GAME_CONFIG_ENEMY_FISH5 0.00125
#define GAME_CONFIG_ENEMY_FISH6 0.00125
//金币的出现机率
#define GAME_CONFIG_ITEM_GOLD 0.005

//吃了一条鱼所加的分数
#define GAME_CONFIG_SCORE_FISH1 1
#define GAME_CONFIG_SCORE_FISH2 1
#define GAME_CONFIG_SCORE_FISH3 2
#define GAME_CONFIG_SCORE_FISH4 3

//吃了一个金币所加的分数
#define GAME_CONFIG_SCORE_ITEM_GOLD 5

//最高分数
#define GAME_CONFIG_MAX_SCORE 999999

//最高关卡
#define GAME_CONFIG_MAX_STAGE 99

#if CC_TARGET_PLATFORM == CC_PLATFORM_WIN32
#define GAME_CONFIG_GLOBAL_FONTNAME_01 "Arial"
#define GAME_CONFIG_GLOBAL_FONTNAME_02 "Arial"
#else
#define GAME_CONFIG_GLOBAL_FONTNAME_01 "Arial-BoldMT"
#define GAME_CONFIG_GLOBAL_FONTNAME_02 "Arial-BoldItalicMT"
#endif

//吃够多少条鱼过一关
#define GAME_CONFIG_STAGE_CLEAR 40 //小鱼+1，中鱼+2，大鱼+3
#define GAME_CONFIG_STAGE_CLEAR_STEP 20 //每过一关，增加的吃鱼条件

//窗口大小
#define GAME_CONFIG_WINDOW_WIDTH 960.0
#define GAME_CONFIG_WINDOW_HEIGHT 640.0

#endif
